config/routes.rb
PresentationsEngine::Engine.routes.draw do
  resources :presentations
end

app/models/presentations_engine/presentation.rb
module PresentationsEngine
  class Presentation < ActiveRecord::Base

  end
end

app/controllers/presentations_engine/application_controller.rb
module PresentationsEngine
  class ApplicationController < ::ApplicationController
    if Rails.env.test?
      layout 'dummy'
    else
      layout 'admin'
    end
  end
end

app/controllers/presentations_engine/presentations_controller.rb
require_dependency "presentations_engine/application_controller"

module PresentationsEngine
  class PresentationsController < ApplicationController
    before_action :find_presentation, only: [:show, :edit, :update, :destroy]

    def index
      @presentations = if params[:filter]
        Presentation.where("date = ?", params[:filter].to_date)
        .order('date')
      elsif params[:search]
        Presentation.where("title ILIKE ?", "%#{params[:search]}%")
      else
        Presentation.all
      end
    end

    def show
    end

    def new
      @presentation = Presentation.new
    end

    def edit
    end

    def create
      @presentation = Presentation.new(presentation_params)
      if @presentation.save
        redirect_to presentations_url, notice:
          'Presentation was successfully created.'
      else
        render 'new'
      end
    end

    def update
      if @presentation.update(presentation_params)
        redirect_to @presentation, notice: 'presentation was successfully updated.'
      else
        render 'edit'
      end
    end

    def destroy
      @presentation.destroy
      redirect_to presentations_url, notice: 'presentation was successfully destroyed.'
    end

    private

    def find_presentation
      @presentation = Presentation.find(params[:id])
    end

    def presentation_params
      params.require(:presentation).permit(:title, :description,
        :user_id, :date)
    end
  end
end

app/helpers/presentations_engine/application_helper.rb
module PresentationsEngine
  module ApplicationHelper
    def method_missing method, *args, &block
      puts "LOOKING FOR ROUTES #{method}"
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          main_app.send(method, *args)
        else
          super
        end
      else
        super
      end
    end

    def respond_to?(method)
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          true
        else
          super
        end
      else
        super
      end
    end
  end
end

app/helpers/presentations_engine/show_dont_tells_helper.rb
module PresentationsEngine
  module PresentationsHelper
   
  end
end

app/views/layouts/show_dont_tells_engine/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShowDontTellsEngine</title>
  <%= stylesheet_link_tag    "show_dont_tells_engine/application", media: "all" %>
  <%= javascript_include_tag "show_dont_tells_engine/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/presentations_engine/presentations/_form.html.haml
= simple_form_for(@presentation, html: { multipart: true }) do |f|
  = render partial: 'shared/errors', locals: { resource: @presentation }
  .col-md-3
    .span3
  .col-md-6
    .span12
      .field
        = f.input :title
      .field
        = f.input :description
      .actions
        = link_to 'Cancel', presentations_path, class: 'btn btn-disabled'
        = f.submit 'Save', class: 'btn'
  .col-md-3
    .span3
  
.clearfix

app/views/presentations_engine/presentations/_presentation.html.haml
%tr
  %td= presentation.title
  %td= presentation.description
  %td= link_to 'Edit', edit_presentation_path(presentation)
  %td= link_to 'Destroy', presentation, method: :delete,
    data: { confirm: 'Are you sure?' }

app/views/presentations_engine/presentations/edit.html.haml
%h1 Editing Presentations
= render 'form'
= link_to 'Show', @presentation
|
= link_to 'Back', presentations_path

app/views/presentations_engine/presentations/index.html.haml
%h1 Listing Presentations
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{ colspan: 3 }
    %tbody
      = render @presentation
%br
= link_to 'New presentation', new_presentation_path

app/views/presentations_engine/presentations/new.html.haml
%h1 New Presentation
= render 'form'
= link_to 'Back', presentations_path

app/views/presentations_engine/presentations/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @presentation.title
%p
  %strong Description:
  = @presentation.description
= link_to 'Edit', edit_presentation_path(@presentation)
|
= link_to 'Back', show_presentation_path